#!/bin/bash

function simple-run {
    src=$1.png
    int=$1.png
    dst=$1-result.png
    shift

    run $src $int $dst $*
}

function run {
    src=$1
    int=$2
    dst=$3
    shift
    shift
    shift

    metatask $src $*
    mv $int $dst
    git checkout $src
}

SCAN_OPTS="--cmds normalize cleanup force-cleanup crop auto-rotate --apply"
#SCANC_OPTS
PRESCAN_OPTS="--cmds crop-prescan --apply"
PHOTO_OPTS="--cmds crop-0px normalize --apply"

simple-run scan-blank $SCAN_OPTS
simple-run scan-blank1 $SCAN_OPTS
simple-run document $SCAN_OPTS
simple-run document2 $SCAN_OPTS
simple-run pre-scan-photo $PRESCAN_OPTS
simple-run scanc-photo $PHOTO_OPTS
#simple-run scanc-blank $SCANC_OPTS
